server:
  port: 8081

# Database configurations
spring:
  application:
    name: course-service

  zipkin:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/universitydb
    username: root
    password: Mostafa@123
    driver-class-name: com.mysql.cj.jdbc.Driver



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

